In [7]:
import numpy as np

#Problem 1

def mylu(A):
    n,m = A.shape
    

    p = np.zeros(n)
    for i in range(n):
        p[i] = i
    p = p.astype(int)


    for k in range(n-1): 
        #find pivot
        pivot = np.argmax(abs(A[p[k:], k])) + k
        
        #swap
        p[pivot], p[k] = p[k], p[pivot]
               
        #multipliers
        mults = A[p[k+1:],k] / A[p[k],k]
        
        #elimination
        A[p[k+1:], k+1:] = A[p[k+1:],k+1:] - np.outer(mults,A[p[k],k+1:])
        A[p[k+1:], k] = mults
        
    return A,p
                          

A, b = getAb()


LU,p = mylu(A)
print(p)

c = forward_subs(LU,p,b)
print(c)

x = backward_subs(LU,p,c)
print(x)


            
        


[2 3 1 0 4]
[ 0.0987     -0.61054152 -1.69805726  2.35015812  2.59163195]
[-4.74452344  5.22095642 -2.29120587  5.31222591 -1.41303909]


In [2]:
#help functions

def forward_subs(LU,P,b):
    ''' Forward substitution algorithm
    Input:
        LU contains both L and U, even if only L is needed here 
        P Integer permutation vector
        b Vector with right hand side in the problem to be solved
    Output:
        c The solution to the linear lower triangular system Lc=b 
    '''
    n, m = LU.shape
    Pb = b[P]
    c = np.zeros(n)
    c[0] = Pb[0]
    for k in range(1,n):
        c[k] = Pb[k] - LU[P[k],0:k] @ c[0:k]
        
    return c

def backward_subs(LU,P,c):
    ''' Backward substitution algorithm
    Input:
        LU contains both L and U, even though just U is needed here
        P Integer permutation vector
        c Vector containing right hand side, i.e. the function solves Ux=c
    Output:
        x Solution to the linear upper triangular system Ux = c
    '''
    n,m = LU.shape
    x = np.zeros(n)
    x[n-1] = c[n-1]/LU[P[n-1],n-1]
    for k in range(n-1,0,-1):
        x[k-1] = (c[k-1]-LU[P[k-1],k:] @ x[k:])/LU[P[k-1],k-1]
        
    return x


def getAb():
    A=np.array([[0.3050, 0.5399, 0.9831, 0.4039, 0.1962],
                [0.2563, -0.1986, 0.7903, 0.6807, 0.5544],
                [0.7746, 0.6253, -0.1458, 0.1704,  0.5167],
                [0.4406, 0.9256, 0.4361, -0.2254, 0.7784],
                [0.4568, 0.2108, 0.6006, 0.3677, -0.8922]])
    b=np.array([0.9876,-1.231,0.0987,-0.5544,0.7712])
    return A,b
